name: Noisy Byte Frontend Tests 
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Add Redis service container
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    # Set up Backend
    - name: Setup Node.js for Backend
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'

    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm ci

    - name: Start Backend Server
      working-directory: ./server
      env:
        REDIS_URL: redis://localhost:6379
        # Add other environment variables your app needs
        NODE_ENV: test
        JWT_SECRET: test-secret
      run: |
        npm run build --if-present
        npm start & # Run in background
        sleep 10 # Wait for server to start