name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: ./server    # Set default working directory for all run steps

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'  # Specify path for cache
    
    - name: Install dependencies
      run: npm ci    # More reliable than npm install for CI environments
      
    - name: Build
      run: npm run build --if-present
      
    - name: Test
      run: npm test
